/*
Generated by Yara-Rules
On 07-10-2021
*/
include "./packers/Javascript_exploit_and_obfuscation.yar"
include "./packers/JJencode.yar"
include "./packers/packer_compiler_signatures.yar"
include "./packers/packer.yar"
include "./packers/peid.yar"
include "./packers/tweetable-polyglot-png.yar"
