# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.x/metricbeat-module-elasticsearch.html

- module: elasticsearch
  #metricsets:
  #  - node
  #  - node_stats
  period: 60s
  hosts: ["http://elasticsearch:9200"]
  #username: "user"
  #password: "secret"
