# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.x/metricbeat-module-kibana.html

- module: kibana
  #metricsets:
  #  - status
  period: 60s
  hosts: ["kibana:5601"]
  #basepath: ""
  #username: "user"
  #password: "secret"
